baseURL: /
languageCode: en
DefaultContentLanguage: en
title: Website of Becki Green
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Becki Green
  customCss: ["css/custom.css"]
  customJs: []
  description: Epidemiologist (she/her)
  displayMode: "dark"
  doNotLoadAnimations: no
  favicon: "favicons/"
  images: 
  keywords: ''
  mainSections: ["About"]
  math:
    enable: no
    use: katex
  profilePicture: "images/RG_image.jpg"
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-orcid
      title: Orcid
      url: https://orcid.org/0000-0002-0513-5188
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/rebecca-e-green/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/beckigreen
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:rebecca.e.green@ucl.ac.uk
  title: Becki Green, PhD

menu:
  main:
    - identifier: bio
      name: About
      url: /
      weight: 300
    - identifier: cv
      name: CV
      url: /work/bgreen_cv.pdf
      weight: 300
 
